<a href="https://colab.research.google.com/github/Syntax-code/Machine-Learning/blob/master/numpy_array_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Jovian Commit Essentials
# Please retain and execute this cell without modifying the contents for `jovian.commit` to work
!pip install jovian --upgrade -q
import jovian
jovian.utils.colab.set_colab_file_id('1wKmpi5UJiq6435C0oj5XDouFXepZ5mFh')

     |████████████████████████████████| 71kB 3.8MB/s 


> ### **Assignment 2 - Numpy Array Operations** 
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
> 
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html 
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 . 
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


# No more Matrix fear when Numpy is here.


### Matrix Initializations using numpy.matlib library.

The most important object defined in NumPy is an N-dimensional array type called ndarray. Matrix is a special case of two dimensional array where each data element is of strictly same size. So every matrix is also a two dimensional array but not vice versa. Matrices are very important data structures for many mathematical and scientific calculations. 

NumPy package contains a Matrix library numpy.matlib. This module has functions that return matrices instead of ndarray objects.

- function 1 = intialize a empty matrix = numpy.matlib.empty()
- function 2 = matrix filled with zeros & ones = numpy.matlib.zeros(), numpy.matlib.ones()
- function 3 = diagonal matrix = numpy.matlib.eye()
- function 4 = Identity matrix = numpy.matlib.identity()
- function 5 = Matrix with random values = numpy.matlib.rand() 

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [2]:
!pip install jovian --upgrade -q

In [3]:
import jovian

In [4]:
jovian.commit(project='numpy-array-operations')

[jovian] Detected Colab notebook...
[jovian] Please enter your API key ( from https://jovian.ai/ ):
API KEY: ··········
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/kartikjchourasiya001/numpy-array-operations


'https://jovian.ai/kartikjchourasiya001/numpy-array-operations'

Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [8]:
import numpy.matlib 
import numpy as np

In [ ]:
# List of functions explained 
function1 = np.matlib.empty
function2 = np.matlib.zeros, np.matlib.ones
function3 = np.matlib.eye
function4 = np.matlib.identity
function5 = np.matlib.rand

## Function 1 - np.matlib.empty

The matlib.empty() function returns a new matrix without initializing the entries.

- numpy.matlib.empty(shape, dtype, order)

In [34]:
# Example 1 - working (change this)
arr1 = np.matlib.empty((2,2)) 

arr2 = np.matlib.empty((3,2), dtype = str) 

print('arr 1 :\n {}\n'.format(arr1))
print('arr 2 :\n {}'.format(arr2))

arr 1 :
 [[1. 1.]
 [1. 1.]]

arr 2 :
 [['' '']
 ['' '']
 ['' '']]


arr1 is filled with random data and the arr2 is empty str matrix. 

In [22]:
# Example 2 - working
arr1 = np.matlib.empty((2,2)) 

arr2 = np.matlib.empty((3,2), dtype = str) 

print('arr1 : {}'.format(arr1.dtype))
print('arr2 : {}'.format(arr2.dtype))

arr1 : float64
arr2 : <U0


data type of the arrays  ----- U - Unicode Strings

In [28]:
# Example 3 - breaking (to illustrate when it breaks)
arr2 = np.matlib.empty((3,2), dtype = str) 

print('arr2 : {}'.format(arr2))

arr1 = np.matlib.empty() 

arr2 : [['' '']
 ['' '']
 ['' '']]


TypeError: ignored

Until and unless the parameters are passed there would be no errors 

So this is how we initialize a empty matrix.

In [36]:
jovian.commit(project = 'numpy-array-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/kartikjchourasiya001/numpy-array-operations


'https://jovian.ai/kartikjchourasiya001/numpy-array-operations'

## Function 2 - np.matlib.zeros, np.matlib.ones

numpy.matlib.zeros()
- This function returns the matrix filled with zeros.

numpy.matlib.ones()
- This function returns the matrix filled with 1s.

In [37]:
# Example 1 - working
arr0 = np.matlib.zeros((2,2)) 

arr1 = np.matlib.ones((2,2))

print('Matrix of zeros :\n {}\n'.format(arr0))
print('Matrix of ones :\n {}\n'.format(arr1))

Matrix of zeros :
 [[0. 0.]
 [0. 0.]]

Matrix of ones :
 [[1. 1.]
 [1. 1.]]



Create matrix filled with ones and zeros

In [39]:
# Example 2 - working
arr0 = np.matlib.zeros((2,2)) 

arr1 = np.matlib.ones((2,2))

print('shape of zeros matrix :\n {}\n'.format(arr0.shape))
print('shape of ones matrix :\n {}\n'.format(arr1.shape))

shape of zeros matrix :
 (2, 2)

shape of ones matrix :
 (2, 2)



Shape of matrix

In [40]:
# Example 3 - breaking (to illustrate when it breaks)
arr0 = np.matlib.zeros((2,2)) 
print('Matrix of zeros :\n {}\n'.format(arr0))

arr1 = np.matlib.ones()
print('Matrix of ones :\n {}\n'.format(arr1))

Matrix of zeros :
 [[0. 0.]
 [0. 0.]]



TypeError: ignored

Until and unless the parameters are passed there would be no errors 

This is how we initialize a zeros and ones matrix

In [42]:
jovian.commit(project = 'numpy-array-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/kartikjchourasiya001/numpy-array-operations


'https://jovian.ai/kartikjchourasiya001/numpy-array-operations'

## Function 3 - np.matlib.eye

This function returns a matrix with 1 along the diagonal elements and the zeros elsewhere.
- numpy.matlib.eye(n, M,k, dtype)

n int
> Number of rows in the output.

M int, optional
> Number of columns in the output, defaults to n.

k int, optional
> Index of the diagonal: 0 refers to the main diagonal, a positive value refers to an upper diagonal, and a negative value to a lower diagonal.

In [47]:
# Example 1 - working
arr = np.matlib.eye(n = 3, M = 4, k = 0, dtype = int)

print(arr)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


Diagonal matrix with main diagonal elements

In [49]:
# Example 2 - working
arr1 = np.matlib.eye(n = 3, M = 4, k = -1, dtype = int)
arr2 = np.matlib.eye(n = 3, M = 4, k = 1, dtype = int) 

print('lower diagonal :\n {}\n'.format(arr1))
print('upper diagonal :\n {}\n'.format(arr2))

lower diagonal :
 [[0 0 0 0]
 [1 0 0 0]
 [0 1 0 0]]

upper diagonal :
 [[0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]



a positive value of k refers to an upper diagonal, and a negative value of k to a lower diagonal.

In [50]:
# Example 3 - breaking (to illustrate when it breaks)
arr = np.matlib.eye( M = 4, k = 0, dtype = int)

print(arr)

TypeError: ignored

Until and unless the parameters are passed there would be no errors 

Here's how we initialize a diagonal matrix

In [51]:
jovian.commit(project = 'numpy-array-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/kartikjchourasiya001/numpy-array-operations


'https://jovian.ai/kartikjchourasiya001/numpy-array-operations'

## Function 4 - np.matlib.identity

The numpy.matlib.identity() function returns the Identity matrix of the given size.
- np.matlib.identity(n, dtype=None)

In [52]:
# Example 1 - working
arr = np.matlib.identity(5, dtype = float)

print(arr)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Identity matrix

In [55]:
# Example 2 - working
arr = np.matlib.identity(5, dtype = int)

print('Sum of all elements of an matrix : {}'.format(np.sum(arr)))

Sum of all elements of an matrix : 5


Sum of all elements of an identity matrix == n

In [56]:
# Example 3 - breaking (to illustrate when it breaks)
arr = np.matlib.identity( dtype = float)

print(arr)

TypeError: ignored

Until and unless the parameters are passed there would be no errors 

Here's how we create a identity matrix

In [57]:
jovian.commit(project = 'numpy-array-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/kartikjchourasiya001/numpy-array-operations


'https://jovian.ai/kartikjchourasiya001/numpy-array-operations'

## Function 5 - np.matlib.rand

The numpy.matlib.rand() function returns a matrix of the given size filled with random values.

In [58]:
# Example 1 - working
arr =np.matlib.rand(3,3) 

print(arr)

[[0.37921614 0.79637346 0.11623672]
 [0.90454757 0.50637468 0.08601273]
 [0.60560438 0.80867143 0.62241797]]


matrix filled with random elements

In [61]:
# Example 2 - working
arr =np.matlib.rand(3,3) 

print('Shape of arr : {}'.format(arr.shape))

Shape of arr : (3, 3)


Shape of matrix

In [62]:
# Example 3 - breaking (to illustrate when it breaks)
arr =np.matlib.rand() 

print(arr)

IndexError: ignored

Until and unless the parameters are passed there would be no errors 

Here's how we initialize a matrix with random elements

In [63]:
jovian.commit(project = 'numpy-array-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/kartikjchourasiya001/numpy-array-operations


'https://jovian.ai/kartikjchourasiya001/numpy-array-operations'

## Conclusion

Initialize arrays with ease with numpy.matlib library

## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html
* ...

In [65]:
jovian.commit(project = 'numpy-array-operations')

[jovian] Detected Colab notebook...
[jovian] Uploading colab notebook to Jovian...
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/kartikjchourasiya001/numpy-array-operations


'https://jovian.ai/kartikjchourasiya001/numpy-array-operations'